# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/new_jeric_core/new_jeric_vivado/project_4/project_4.runs/synth_1/bd_target_fpga_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 6
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/new_jeric_core/new_jeric_vivado/project_4/project_4.cache/wt [current_project]
set_property parent.project_path D:/new_jeric_core/new_jeric_vivado/project_4/project_4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.2 [current_project]
set_property ip_repo_paths d:/new_jeric_core/bd_target_fpga/ip [current_project]
update_ip_catalog
set_property ip_output_repo d:/new_jeric_core/new_jeric_vivado/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs D:/new_jeric_core/new_jeric_core_folder/processor [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files c:/Users/Alyssa/AppData/Roaming/rv32imc_gf22/pipelined-RV32IMC-GF22/assembly_dual_core_test_cases/inst_mem/uart_core0.coe
add_files c:/Users/Alyssa/AppData/Roaming/rv32imc_gf22/pipelined-RV32IMC-GF22/assembly_dual_core_test_cases/inst_mem/uart_core1.coe
add_files c:/Users/Alyssa/AppData/Roaming/rv32imc_gf22/pipelined-RV32IMC-GF22/assembly_dual_core_test_cases/data_mem/uart_msg.coe
add_files d:/new_jeric_core/new_jeric_core_folder/assembler/uart_test.coe
add_files d:/new_jeric_core/new_jeric_core_folder/assembler/uart_test_data.coe
read_verilog -library xil_defaultlib D:/new_jeric_core/bd_target_fpga/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/hdl/bd_target_fpga_wrapper.v
add_files D:/new_jeric_core/bd_target_fpga/bd_target_fpga.bd
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_clk_wiz_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_clk_wiz_0_0/bd_target_fpga_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_clk_wiz_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_clk_wiz_0_0/bd_target_fpga_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_clk_wiz_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_clk_wiz_0_0/bd_target_fpga_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_0_0/bd_target_fpga_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_0_0/bd_target_fpga_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_0_0/bd_target_fpga_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_blk_mem_gen_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_blk_mem_gen_0_0/bd_target_fpga_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_blk_mem_gen_1_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_blk_mem_gen_1_0/bd_target_fpga_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_0/bd_02ea_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_1/bd_02ea_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_2/bd_02ea_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_3/bd_02ea_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_4/bd_02ea_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_8/bd_02ea_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_9/bd_02ea_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_9/bd_02ea_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_10/bd_02ea_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_10/bd_02ea_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_11/bd_02ea_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_11/bd_02ea_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_12/bd_02ea_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_12/bd_02ea_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_13/bd_02ea_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_13/bd_02ea_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_17/bd_02ea_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_18/bd_02ea_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_18/bd_02ea_sarn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_19/bd_02ea_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_19/bd_02ea_srn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_20/bd_02ea_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_20/bd_02ea_sawn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_21/bd_02ea_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_21/bd_02ea_swn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_22/bd_02ea_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_22/bd_02ea_sbn_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_26/bd_02ea_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_27/bd_02ea_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_27/bd_02ea_sarn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_28/bd_02ea_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_28/bd_02ea_srn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_29/bd_02ea_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_29/bd_02ea_sawn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_30/bd_02ea_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_30/bd_02ea_swn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_31/bd_02ea_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_31/bd_02ea_sbn_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_32/bd_02ea_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_33/bd_02ea_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_33/bd_02ea_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_34/bd_02ea_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_34/bd_02ea_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_35/bd_02ea_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_35/bd_02ea_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_36/bd_02ea_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_36/bd_02ea_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_37/bd_02ea_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_37/bd_02ea_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_39/bd_02ea_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_40/bd_02ea_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_40/bd_02ea_m01arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_41/bd_02ea_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_41/bd_02ea_m01rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_42/bd_02ea_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_42/bd_02ea_m01awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_43/bd_02ea_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_43/bd_02ea_m01wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_44/bd_02ea_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_44/bd_02ea_m01bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_46/bd_02ea_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_47/bd_02ea_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_47/bd_02ea_m02arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_48/bd_02ea_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_48/bd_02ea_m02rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_49/bd_02ea_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_49/bd_02ea_m02awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_50/bd_02ea_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_50/bd_02ea_m02wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_51/bd_02ea_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/bd_0/ip/ip_51/bd_02ea_m02bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_axi_uartlite_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_axi_uartlite_0_0/bd_target_fpga_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_axi_uartlite_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_axi_uartlite_0_0/bd_target_fpga_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_axi_uartlite_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_axi_uartlite_0_0/bd_target_fpga_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_blk_mem_gen_2_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_blk_mem_gen_2_0/bd_target_fpga_blk_mem_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_1_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_1_0/bd_target_fpga_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_1_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_1_0/bd_target_fpga_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_1_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_proc_sys_reset_1_0/bd_target_fpga_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_mig_7series_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_mig_7series_0_0/bd_target_fpga_mig_7series_0_0/user_design/constraints/bd_target_fpga_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/ip/bd_target_fpga_mig_7series_0_0/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_mig_7series_0_0/bd_target_fpga_mig_7series_0_0/user_design/constraints/bd_target_fpga_mig_7series_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Alyssa/AppData/Roaming/Xilinx/Vivado/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Alyssa/AppData/Roaming/Xilinx/Vivado/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Alyssa/AppData/Roaming/Xilinx/Vivado/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Alyssa/AppData/Roaming/Xilinx/Vivado/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_system_ila_0_0/bd_0/ip/ip_0/bd_d105_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Alyssa/AppData/Roaming/Xilinx/Vivado/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_system_ila_0_0/bd_0/bd_d105_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Alyssa/AppData/Roaming/Xilinx/Vivado/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/ip/bd_target_fpga_system_ila_0_0/bd_target_fpga_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/new_jeric_core/bd_target_fpga/for_target_fpga_cached.gen/sources_1/bd/bd_target_fpga/bd_target_fpga_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/new_jeric_core/new_jeric_core_folder/constraints/arty7_a200t_nexys.xdc
set_property used_in_implementation false [get_files D:/new_jeric_core/new_jeric_core_folder/constraints/arty7_a200t_nexys.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/new_jeric_core/new_jeric_vivado/project_4/project_4.srcs/utils_1/imports/synth_1/core_extmem.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top bd_target_fpga_wrapper -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bd_target_fpga_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file bd_target_fpga_wrapper_utilization_synth.rpt -pb bd_target_fpga_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
